name: book_test
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  uuid: ^2.2.2
  moor: ^3.4.0
  sqlite3_flutter_libs: ^0.2.0
  path_provider: ^1.6.22
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_driver_helper: ^1.1.1
  moor_generator: ^3.4.0
  build_runner: ^1.10.4


flutter:
  uses-material-design: true


